
# ~/.config/starship.toml

# Use custom format
# format = """x"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true


[directory]
disabled = true
# truncation_length = 8
# fish_style_pwd_dir_length = 3
# truncation_symbol = "…/"

# [directory.substitutions]
# "/" = "/"

[custom.cwd]
# command = """ echo "$PWD" | sed -e "s!$HOME!~!" | sed "s/\\//$(printf "\\033[1;33m\\/\\033[0;37m")/g" """
command = """ echo "$PWD" | sed -e "s!$HOME!~!" | sed -re "s!([^/]{3})[^/]{3,}+/!\\1…/!g" | sed "s/\\//$(printf "\\033[1;33m\\/\\033[0;37m")/g" """
when = "true"
shell = ["sh"]

#directories = ["emareg", "Dokumente"]
#command = """ echo "$PWD" | sed "s/\\//$(printf "\\033[1;33m\\/\\033[0;37m")/g" """
#format = " transcending [$output]($style)"

